# The MIT License (MIT)
# Copyright © 2023 Yuma Rao
# TODO(developer): Set your name
# Copyright © 2023 <your name>

# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the “Software”), to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all copies or substantial portions of
# the Software.

# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
# THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

__version__ = "1.2.0"
version_split = __version__.split(".")
__spec_version__ = (
    (1000 * int(version_split[0]))
    + (10 * int(version_split[1]))
    + (1 * int(version_split[2]))
)

import os
from openai import AsyncOpenAI
AsyncOpenAI.api_key = os.environ.get('OPENAI_API_KEY')
if not AsyncOpenAI.api_key:
    raise ValueError("Please set the OPENAI_API_KEY environment variable.")

client = AsyncOpenAI(timeout=60.0)

# Blacklist variables
ALLOW_NON_REGISTERED = False
PROMPT_BLACKLIST_STAKE = 20000
IMAGE_BLACKLIST_STAKE = 20000
EMBEDDING_BLACKLIST_STAKE = 20000
ISALIVE_BLACKLIST_STAKE = min(PROMPT_BLACKLIST_STAKE, IMAGE_BLACKLIST_STAKE)
MIN_REQUEST_PERIOD = 2
MAX_REQUESTS = 40
# must have the test_key whitelisted to avoid a global blacklist
testnet_key = "5EhEZN6soubtKJm8RN7ANx9FGZ2JezxBUFxr45cdsHtDp3Uk"
test_key = "5DcRHcCwD33YsHfj4PX5j2evWLniR1wSWeNmpf5RXaspQT6t"
corcel = "5Hddm3iBFD2GLT5ik7LZnT3XJUnRnN8PoeCFgGQgawUVKNm8"
WHITELISTED_KEYS = [testnet_key, test_key, corcel]

weight_copiers = [117,224,214,104,2,102,7,135,114,251,4]
threat_keys = [251]
BLACKLISTED_KEYS = weight_copiers + threat_keys + []
validators_running_wandb = [0, 1, 16, 26, 81, 103, 109, 113, 124, 178, 244]

PROJECT_NAMES = ['embeddings-data', 'synthetic-QA-v2', 'synthetic-images']
PROJECT_NAME = 'multi-modality'


# Instruct themes used in https://arxiv.org/pdf/2304.12244.pdf to train WizardLM
initial_instruct_themes = ['Philosopy', 'Technology', 'Physics', 'Ethics', 'Academic Writing', 'Economy', 'History', 'Medicine', 'Toxicity', 'Roleplay', 'Entertainment', 'Biology', 'Counterfactual', 'Literature', 'Chemistry', 'Writing', 'Sport', 'Law', 'Language', 'Computer Science', 'Multilangual', 'Common Sense', 'Art', 'Complex Format' 'Code Generation', 'Math', 'Code Debug', 'Reasoning']
more_instruct_themes = [
    "Global Cultures and Societies",
    "Modern and Ancient Civilizations",
    "Innovations in Science and Technology",
    "Environmental Conservation and Biodiversity",
    "World Religions and Philosophical Thought",
    "Global Economy and International Trade",
    "Public Health and Pandemic Response",
    "Human Rights and Social Justice Issues",
    "Political Systems and International Relations",
    "Major Historical Events and their Impact",
    "Advancements in Medicine and Healthcare",
    "Fundamentals of Physics and the Cosmos",
    "Cognitive Development and Learning Theories",
    "Sustainable Development and Green Technologies",
    "Media Literacy and News Analysis",
    "Classical and Modern Literature",
    "Fundamentals of Mathematics and Logic",
    "Social Psychology and Group Dynamics",
    "Emerging Trends in Education",
    "Civic Engagement and Community Organizing"
    ]
INSTRUCT_DEFAULT_THEMES = initial_instruct_themes + more_instruct_themes
INSTRUCT_DEfAULT_QUESTIONS = None

CHAT_DEFAULT_THEMES = ['Love and relationships', 'Nature and environment', 'Art and creativity', 'Technology and innovation', 'Health and wellness', 'History and culture', 'Science and discovery', 'Philosophy and ethics', 'Education and learning', 'Music and rhythm', 'Sports and athleticism', 'Food and nutrition', 'Travel and adventure', 'Fashion and style', 'Books and literature', 'Movies and entertainment', 'Politics and governance', 'Business and entrepreneurship', 'Mind and consciousness', 'Family and parenting', 'Social media and networking', 'Religion and spirituality', 'Money and finance', 'Language and communication', 'Human behavior and psychology', 'Space and astronomy', 'Climate change and sustainability', 'Dreams and aspirations', 'Equality and social justice', 'Gaming and virtual reality', 'Artificial intelligence and robotics', 'Creativity and imagination', 'Emotions and feelings', 'Healthcare and medicine', 'Sportsmanship and teamwork', 'Cuisine and gastronomy', 'Historical events and figures', 'Scientific advancements', 'Ethical dilemmas and decision making', 'Learning and growth', 'Music genres and artists', 'Film genres and directors', 'Government policies and laws', 'Startups and innovation', 'Consciousness and perception', 'Parenting styles and techniques', 'Online communities and forums', 'Religious practices and rituals', 'Personal finance and budgeting', 'Linguistic diversity and evolution', 'Human cognition and memory', 'Astrology and horoscopes', 'Environmental conservation', 'Personal development and self-improvement', 'Sports strategies and tactics', 'Culinary traditions and customs', 'Ancient civilizations and empires', 'Medical breakthroughs and treatments', 'Moral values and principles', 'Critical thinking and problem solving', 'Musical instruments and techniques', 'Film production and cinematography', 'International relations and diplomacy', 'Corporate culture and work-life balance', 'Neuroscience and brain function', 'Childhood development and milestones', 'Online privacy and cybersecurity', 'Religious tolerance and understanding', 'Investment strategies and tips', 'Language acquisition and fluency', 'Social influence and conformity', 'Space exploration and colonization', 'Sustainable living and eco-friendly practices', 'Self-reflection and introspection', 'Sports psychology and mental training', 'Globalization and cultural exchange', 'Political ideologies and systems', 'Entrepreneurial mindset and success', 'Conscious living and mindfulness', 'Positive psychology and happiness', 'Music therapy and healing', 'Film analysis and interpretation', 'Human rights and advocacy', 'Financial literacy and money management', 'Multilingualism and translation', 'Social media impact on society', 'Religious extremism and radicalization', 'Real estate investment and trends', 'Language preservation and revitalization', 'Social inequality and discrimination', 'Climate change mitigation strategies', 'Self-care and well-being', 'Sports injuries and rehabilitation', 'Artificial intelligence ethics', 'Creativity in problem solving', 'Emotional intelligence and empathy', 'Healthcare access and affordability', 'Sports analytics and data science', 'Cultural appropriation and appreciation', 'Ethical implications of technology']
CHAT_DEFAULT_QUESTIONS = ['What is the most important quality you look for in a partner?', 'How do you define love?', 'What is the most romantic gesture you have ever received?', 'What is your favorite love song and why?', 'What is the key to a successful long-term relationship?', 'What is your idea of a perfect date?', 'What is the best piece of relationship advice you have ever received?', 'What is the most memorable love story you have heard?', 'What is the biggest challenge in maintaining a healthy relationship?', 'What is your favorite way to show someone you love them?']

IMAGE_DEFAULT_THEMES = ["Urban Echoes", "Nature's Whispers", "Futuristic Visions", "Emotional Abstracts", "Memory Fragments", "Mythical Echoes", "Underwater Mysteries", "Cosmic Wonders", "Ancient Secrets", "Cultural Tapestries", "Wild Motion", "Dreamlike States", "Seasonal Shifts", "Nature's Canvas", "Night Lights", "Historical Shadows", "Miniature Worlds", "Desert Dreams", "Robotic Integrations", "Fairy Enchantments", "Timeless Moments", "Dystopian Echoes", "Animal Perspectives", "Urban Canvas", "Enchanted Realms", "Retro Futures", "Emotive Rhythms", "Human Mosaics", "Undersea Unknowns", "Mystical Peaks", "Folklore Reimagined", "Outer Realms", "Vintage Styles", "Urban Wilderness", "Mythical Retellings", "Colorful Breezes", "Forgotten Places", "Festive Illuminations", "Masked Realities", "Oceanic Legends", "Digital Detachments", "Past Reverberations", "Shadow Dances", "Future Glimpses", "Wild Forces", "Steampunk Realms", "Reflective Journeys", "Aerial Grace", "Microscopic Worlds", "Forest Spirits"]
IMAGE_DEFAULT_QUESTIONS = ['A majestic golden eagle soaring high above a mountain range, its powerful wings spread wide against a clear blue sky.', 'A bustling medieval marketplace, full of colorful stalls, various goods, and people dressed in period attire, with a castle in the background.', 'An underwater scene showcasing a vibrant coral reef teeming with diverse marine life, including fish, sea turtles, and starfish.', 'A serene Zen garden with neatly raked sand, smooth stones, and a small, gently babbling brook surrounded by lush green foliage.', 'A futuristic cityscape at night, illuminated by neon lights, with flying cars zooming between towering skyscrapers.', 'A cozy cabin in a snowy forest at twilight, with warm light glowing from the windows and smoke rising from the chimney.', 'A surreal landscape with floating islands, cascading waterfalls, and a path leading to a castle in the sky, set against a sunset backdrop.', 'An astronaut exploring the surface of Mars, with a detailed spacesuit, the red Martian terrain around, and Earth visible in the sky.', 'A lively carnival scene with a Ferris wheel, colorful tents, crowds of happy people, and the air filled with the smell of popcorn and cotton candy.', 'A majestic lion resting on a savanna, with the African sunset in the background, highlighting its powerful mane and serene expression.']

IMAGE_THEMES = [
    'The Dance of Textures',
    'Eternal Fragility',
    'Whispers of the Sea',
    'Emotional Landscapes',
    'Magical Realism',
    'Celestial Melodies',
    'Sculpting Emotions',
    'Embracing Imperfections',
    'Colorful Abstractions',
    'Infinite Fragments',
    'Celestial Rhythms',
    'Reflections of Light',
    'Celestial wonders',
    'Luminous Reflections',
    'Merging Dimensions',
    'Surreal Reflections',
    'Shadows and light',
    'Emerging Energy',
    'Sculpting Memories',
    'Cosmic Kaleidoscope',
    'Soulful Expressions',
    'Infinite Horizons',
    'Unseen Dimensions',
    'Fragments of Life',
    'Shattered Illusions',
    'Tranquil Transcendence',
    'Melancholic Whimsy',
    'Harmonious Fusion',
    'Spectral Visions',
    'Whispering Whimsy',
    'Dancing with Fire',
    'Enchanted Forests',
    'Vibrant Serenade',
    'Hidden Meanings',
    'Harmony of Colors',
    'Merging Horizons',
    'Colorful Illusions',
    'Whimsical Wonders',
    'Abstract Landscapes',
    'Whispers of Serenity',
    'Exploring Identity',
    'Harmony in chaos',
    'The Symphony of Life',
    'The Beauty of Decay',
    'Mystical Melodies',
    'Transcending Time',
    'Transcendent Transitions',
    'Unleashing Creativity',
    'The Magic of Details',
    'Fleeting Moments',
    'Chasing Sunsets',
    'Symphony of colors',
    'Ethereal Elegance',
    'Dreams of Tomorrow',
    'Fleeting Eternity',
    'Mystical creatures',
    'Mystical Enchantments',
    'Unseen Realities',
    'Sculpted Emotions',
    'Fluid Dynamics',
    'Eternal Reflections',
    'Temporal Illusions',
    'Luminous Depths',
    'The Alchemy of Creation',
    'Vivid Dreamscape',
    'Transcendent Moments',
    'The Language of Shapes',
    'Harvesting Hope',
    'Symphony of Colors',
    'Whimsical Wonders',
    'Urban Exploration',
    'The Fragments of Time',
    'Harmony in Chaos',
    'The Beauty Within',
    'Evolving Textures',
    'Breaking Barriers',
    'Fragments of Time',
    'Whispering Whirlwinds',
    'Rhythms of Life',
    'Hidden Beauty',
    'Reflections of Life',
    'Captivating Chaos',
    'Metamorphosis of Form',
    'Mystical Enchantment',
    'The Human Experience',
    'Layers of Identity',
    'Luminous Visions',
    'Emerging Identity',
    'Unspoken narratives',
    'Journey into darkness',
    'Visions of tomorrow',
    'Whispers of the Earth',
    'Unveiling the Invisible',
    'Whirlwind of Colors',
    'Rhythm of Creation',
    'Innermost Thoughts',
    'Reflections of Identity',
    'Ethereal Abstractions',
    'Whispering Shadows',
    'The Harmony of Shapes',
    'Cosmic Energy',
    'Inner reflections',
    'Symphony of Solitude',
    'Dancing with Shadows',
    'Celestial Harmony',
    'Enchanted Visions',
    'Whispers of Inspiration',
    'Surreal Serenade',
    'Transcendent Bliss',
    'The Dance of Light',
    'Dancing Shadows',
    'Whispering Dreams',
    'Embracing Imperfections',
    'Infinite possibilities',
    'Mystic Reverie',
    'Metamorphosis',
    'Harvesting Memories',
    'Enigmatic Reflections',
    'Ethereal Dreams',
    'Melodies of Nature',
    'Layers of Existence',
    'Whispers of the Wind',
    'Enigmatic Beauty',
    'Whirling Vortex',
    'Echoes of Eternity',
    'The Souls Journey',
    'Whispered secrets',
    'Curiosity Unleashed',
    'Whispering Tides',
    'Dreamlike Journeys',
    'Merging Perspectives',
    'Dreams of Flight',
    'Urban Poetry',
    'The Mystery of Shadows',
    'Celestial Wonders',
    'Dreams of flight',
    'Eternal Motion',
    'Enigmatic Euphoria',
    'Unspoken Stories',
    'Spectral Melodies',
    'Emerging Patterns',
    'Shadows of Tomorrow',
    'Dreamlike Realities',
    'Whimsical Wonderlands',
    'The Melody of Light',
    'Visions of Tomorrow',
    'Capturing emotions',
    'The Dance of Life',
    'Exploring Contrasts',
    'Echoes of the Past',
    'Dreams and Nightmares',
    'Abstract Whispers',
    'Vibrant Serendipity',
    'Harmony in Contrast',
    'Chromatic Whispers',
    'Hidden Treasures',
    'Celestial Beauty',
    'Ethereal landscapes',
    'Whirling Dervishes',
    'Journey to the Soul',
    'Translucent Dreams',
    'Symphony of Life',
    'Echoes of Silence',
    'Enchanted Melodies',
    'Enchanted Reverie',
    'Tangled Thoughts',
    'Vibrant Rhythms',
    'Metamorphosis of Light',
    'Whispers of Nature',
    'Mysteries of Time',
    'Dancing with Colors',
    'Eternal Serenade',
    'Translucent Veils',
    'Whispers of the Past',
    'The Art of Silence',
    'Whimsical Whispers',
    'Embracing Vulnerability',
    'Mystical Waters',
    'Parallel Universes',
    'Sculpting Shadows',
    'Fluid Movements',
    'Reimagined Landscapes',
    'Illusions of Light',
    'Temporal Echoes',
    'Ethereal Beauty',
    'Euphoric Euphony',
    'The Magic Within',
    'Ethereal Visions',
    'Unraveling Mysteries',
    'Rhythms of nature',
    'Visions of Tomorrow',
    'Eternal Transcendence',
    'The Whispers of Wind',
    'The Power of Music',
    'Celestial Fusion',
    'Harmonic Fusion',
    'The Energy of Life',
    'Whirling Energies',
    'Enchanted Forest',
    'Serenade of Seasons',
    'Shades of Solitude',
    'Surreal Visions Unveiled',
    'Magical Realms',
    'Transcendent Transparencies',
    'Interstellar Dreams',
    'Celestial Fragments',
    'Whirling Fantasies',
    'Vibrant Echoes',
    'Luminous Journeys',
    'Soulful Melodies',
    'Merging Horizons',
    'Whispers of Light',
    'Cascading Light',
    'Enigmatic Landscapes',
    'Forgotten Memories',
    'Soothing Chaos',
    'Transcending Boundaries',
    'The Fragility of Time',
    'Shimmering Dreamscape',
    'Chasing Illusions',
    'Interwoven Narratives',
    'Euphoria in Motion',
    'Echoes of Emotion',
    'Rhythm of the Universe',
    'Inner Reflections',
    'Melodies of the Soul',
    'Abstract Expressions',
    'Symphony of Life',
    'Enigmatic Fragments',
    'Untamed Wildness',
    'Cosmic Connections',
    'The Serenity of Space',
    'Fragments of memories',
    'Colorful Whispers',
    'Evolving identities',
    'Whispers of Memories',
    'Imaginary Landscapes',
    'Emotional Portraits',
    'Hidden Dimensions',
    'Ethereal Reflections',
    'Hidden Messages',
    'Whispering Echoes',
    'Melting Boundaries',
    'Journey of Discovery',
    'Urban Melancholy',
    'Unveiling Truths',
    'Ephemeral Eternity',
    'Melting Colors',
    'Celestial Serenity',
    'Textures of Life',
    'Eternal Fragments',
    'Evolving Patterns',
    'Journey Through Time',
    'Harmony in Disarray',
    'Fragments of Eternity',
    'Chasing Shadows',
    'The Beauty of Movement',
    'Timeless Beauty',
    'The Power of Contrast',
    'Whispers of Silence',
    'Dreams in Motion',
    'Captivating Fragments',
    'Surreal Visions',
    'Abstract Emotions',
    'Unveiled Secrets',
    'Whispers of the Heart',
    'Unveiling Shadows',
    'Exploring Boundaries',
    'A Glimpse of Eternity',
    'Surreal Landscapes',
    'Dreams that Soar',
    'Harmony of Contrasts',
    'Dreamlike Landscapes',
    'Whimsical Dreams',
    'Shadows and Light',
    'Essence of Life',
    'Infinite Textures',
    'Cascading Colors',
    'Harvest of Memories',
    'Rhythmic Movements',
    'The Magic of Water',
    'Captivating Contrasts',
    'Surreal Wonderland',
    'The Essence of Dreams',
    'Rhythmic Abstractions',
    'Dreamlike Visions',
    'Unveiling Illusions',
    'Abstract Narratives',
    'Melancholic Melodies',
    'Interstellar Symphony',
    'Rhythms of Imagination',
    'The Spirit of Movement',
    'Lyrical Brushstrokes',
    'Suspended Animation',
    'Infinite Love',
    'Canvas of Dreams',
    'Evolving Perspectives',
    'Serenity in chaos',
    'Serenity in Chaos',
    'Cosmic Rhythms',
    'Melancholic Whispers',
    'Painted Passions',
    'Serenading Colors',
    'Unveiling the Unseen',
    'The Spirit of Freedom',
    'Urban Melodies',
    'Infinite Imagination',
    'Whispered Secrets Revealed',
    'Cityscapes at Dusk',
    'Wandering Thoughts',
    'Cosmic connections',
    'Infinite Possibilities',
    'Vibrant Whispers',
    'Fragments of Memory',
    'Abstract Harmony',
    'Unveiling the Unknown',
    'Shaping Time',
    'Beyond the Surface',
    'Mystical Reflections',
    'The Power of Silence',
    'Whispers of Inspiration',
    'Symphony of Shadows',
    'Whimsical Wonderland',
    'Rhythm of the Elements',
    'Emerging Dimensions',
    'Whispers of the Universe',
    'Timeless elegance',
    'The Art of Imperfection',
    'Infinite Perspectives',
    'Emerging from Shadows',
    'Shifting Perspectives',
    'Textures of existence',
    'Whispers of Creation',
    'Dancing Brushstrokes',
    'Ethereal Whispers',
    'Surreal Landscapes',
    'Ethereal Explorations',
    'Reflections of the Soul',
    'Whimsical Journey',
    'Harmony in contrast',
    'Evolving Perspectives',
    'Embracing Shadows',
    'Enigmatic Elegance',
    'Celestial Rapture',
    'Chaos and Order',
    'Transcending Boundaries',
    'Serenading Silence',
    'Symmetry in Chaos',
    'Cosmic Serenity',
    'Enigmatic Depths',
    'Underwater Fantasies',
    'Abstract Realities',
    'Surreal Symphony',
    'Metamorphosis of Life',
    'Cosmic Exploration',
    'Liberating Limitations',
    'Rhythm of Life',
    'The Power of Words',
    'Fragmented Realities',
    'Melodies of Color',
    'The Language of Symbols',
    'Ethereal Essence',
    'Enchanted Horizons',
    'Echoes of Time',
    'Journey Within',
    'Serenity in Chaos',
    'The Art of Shadows',
    'Transcending Dimensions',
    'Mosaic of Memories',
    'Intertwined Destinies',
    'Reverie of Light',
    'Metamorphosis of Self',
    'Melodies of life',
    'Whirlwind of Emotions',
    'Mystical Serenity',
    'Celestial Harmonies',
    'The Dance of Nature',
    'Cosmic Vibrations',
    'Transcendent Whispers',
    'Timeless Elegance',
    'Melodies of the Mind',
    'The Power of Imagination',
    'Celestial Visions',
    'The Fragility of Love',
    'Temporal Fragments',
    'Surreal Symphony',
    'Ephemeral Beauty',
    'Sensory Overload',
    'Melodies of Light',
    'Whirling Emotions',
    'Rhythms of the Mind',
    'The Language of Dreams',
    'Imaginary Journeys',
    'The Poetry of Light',
    'Spectral Illusions',
    'Ancient Mysteries',
    'Captivating Illusions',
    'The Fluidity of Nature',
    'Unseen Emotions',
    'Unraveling Time',
    'Ethereal Serenity',
    'Evolving Fragments',
    'Whispering Waves',
    'Harmony in disarray',
    'Abstracted Nature',
    'Journey to Nowhere',
    'Captivating Curiosity',
    'Eternal Moments',
    'Eternal Enigma',
    'Abstract impressions',
    'Uncharted Realms',
    'Journey of self',
    'Serenade of Colors',
    'The Inner Journey',
    'Reflections of Self',
    'Embracing the Unknown',
    'Journey to Infinity',
    'Metamorphosis of nature',
    'Melodies of the Universe',
    'Transcendent Silence',
    'Magical realism',
    'Echoes of Nature',
    'Redefining Boundaries',
    'Vibrant Visions',
    'Whispers of the Mind',
    'Parallel Realities',
    'Exploring Inner Landscapes',
    'Reimagining Reality',
    'Rhythms of the Soul',
    'Unexpected Connections',
    'Metamorphosis of Color',
    'Melodies of the Heart',
    'Sculpted Memories',
    'Hidden Realities',
    'Mystic Visions',
    'Whirling Dreams',
    'Vibrant Energy',
    'Dancing Colors',
    'Uncharted Horizons',
    'Ethereal Dreamscape',
    'Serenade of Shadows',
    'Whirling Energy',
    'Shades of Serenity',
    'Vibrant Whirlwind',
    'Sculpted Illusions',
    'Abstracted Realities',
    'Cosmic Dreamscape',
    'Uncharted territories',
    'Interplay of elements',
    'Urban Rhythms',
    'Abstract Reflections',
    'Exploring the Void',
    'Dancing Fireflies',
    'Luminous Landscapes',
    'Enigmatic Portraits',
    'Exploring the Unknown',
    'Melodies of Life',
    'Mystic Reflections',
    'Emerald Dreamscape',
    'Harmony in Motion',
    'Reimagined Realities',
    'Capturing Essence',
    'Surreal Symmetry',
    'Evolving Energies',
    'Enigmatic Serenity',
    'Urban Jungle Dreams',
    'Enigmatic portraits',
    'Surreal Serenity',
    'Surreal Portraits',
    'Emotions Unleashed',
    'Enchanted Forest Tales',
    'Whispers of the Night',
    'Harmonic Convergence',
    'Wandering Imagination',
    'Cultural Fusion',
    'Stardust Symphony',
    'Vibrant Abstractions',
    'Translucent Depths',
    'The Essence of Time',
    'Surreal Whispers',
    'Unveiling mysteries',
    'Rhythmic Landscapes',
    'Vibrant energy',
    'Whispers of Dreams',
    'Exploring duality',
    'Translucent Veil',
    'Sensory Delights',
    'Spectral Whispers',
    'Illusive Realms',
    'Parallel Dimensions',
    'Harvesting Dreams',
    'Whimsical Adventures',
    'Merging Realities',
    'The Essence of Life',
    'Harmonious Chaos',
    'The Power of Color',
    'Rhythms of Nature',
    'Whimsical Abstractions',
    'Whispers of Time',
    'Transcendent moments',
    'Cosmic Journey',
    'Exploring the unknown',
    'Unveiling Beauty',
    'Melting Horizons',
    'Unspoken Emotions',
    'Mystical Journeys',
    'Emerging Realities',
    'Colorful abstractions',
    'Dancing with light',
    'Uncharted Territories',
    'Celestial Awakening',
    'Organic Abstractions',
    'Whispered Secrets',
    'Alchemy of Expression',
    'Essence of life',
    'Symphony of Shapes',
    'The Mystery Within',
    'Stardust Melodies',
    'The Spirit of Adventure',
    'Unlocking Imagination',
    'Celestial Beings',
    'The Rhythm of Life',
    'Symphony of Dreams',
    'Harmonious Contrasts',
    'Vibrant Dreamscape',
    'Fluid Abstractions',
    'Vibrant Reflections',
    'Ephemeral Moments',
    'Journey of Colors',
    'The Dance of Fire',
    'Serenade of Silence',
    'Dreamscapes',
    'Mystical Creatures',
    'Embracing the Chaos',
    'Emotional Journeys',
    'Melting Time',
    'Dancing with Light',
    'Whispering Whispers',
    'Blissful Serenity',
    'Emerging Whispers',
    'Evolving Dimensions',
    'Whispering Winds',
    'The Language of Flowers',
    'Eternal Echoes',
    'The Poetry of Light',
    'The Art of Stillness',
    'Serenade of Light',
    'Celestial Symphony',
    'Enigmatic Visions',
    'Mystical Landscapes',
    'Textures of Time',
    'Journey of Light',
    'Colorful Chaos',
    'Whispered Stories',
    'The Essence of Light',
    'The Power Within',
    'Captivating Rhythms',
    'Evolving Realities',
    'Dreamlike Diversions',
    'Enchanted Realms',
    'Symphony of Textures',
    'Fleeting Moments Frozen',
    'Spectrum of Emotions',
    'The Colors of Sound',
    'The Souls Canvas',
    'Abstracting Reality',
    'Immersive Portals',
    'The Language of Colors',
    'The Symphony of Colors',
    'Celestial Whispers',
    'Uncharted Waters',
    'Whimsical Wonder',
    'Whispers of the Soul',
    'Captivating Curves',
    'The Essence of Silence',
    'The Chaos of Creation',
    'The Beauty of Imperfection',
    'Chromatic Symphony',
    'Juxtaposed Elements',
    'Sculpting Time',
    'The Art of Balance',
    'Unseen Connections',
    'Enchanted Abstractions',
    'Infinite Echoes',
    'Celestial Serenade',
    'Vibrant Chaos',
    'Sonic Landscapes',
    'Ephemeral beauty',
    'Unseen Perspectives',
    'Emerging Horizons',
    'Embracing imperfections',
    'Ephemeral Fragments',
    'Unfolding Stories',
    'Unseen dimensions',
    'Ephemeral Essence',
    'Parallel Universes Collide',
    'Whirling Motion',
    'Fleeting Fragments',
    'Shades of Serendipity',
    'Urban rhythms',
    'Silent Echoes',
    'Mosaic of Dreams',
    'Evolving Identities',
    'Theatrical Illusions',
    'Mystical Portals',
    'Emotional landscapes',
    'The Symphony of Senses',
    'Whispers of the past',
    'Layers of Perception',
    'Mystic Mosaic',
    'Rhythm of the Soul',
    'Abstracted Memories',
    'Surreal visions',
    'Embracing the wild',
    'Perpetual Motion',
    'Vibrant Contrasts',
    'Fusion of Elements',
    'Rhythmic Patterns',
    'Whispers of the soul',
    'Journey of the Soul',
    'Metamorphic Dreams',
    'Whispering Canvases',
    'Infinite Reflections',
    'The Human Connection',
    'Captured Essence',
    'Sculpted Whispers',
    'Shadows of the Mind',
    'Whispers of the Sky',
    'Whispers of Wonder',
    'Shaping Memories',
    'The Power of Light',
    'Abstract Euphoria',
    'Invisible Connections',
    'Cosmic Harmony',
    'Reflections of Time',
    'Human Connections',
    'Whirling Colors',
    'The Essence of Love',
    'Whimsical dreams',
    'Echoes of silence',
    'Transcendent Beauty',
    'Symphony of Light',
    'Whispered Whimsy',
    'Untamed Imagination',
    'Transcendent Echoes',
    'Shattered Realities',
    'Embracing Chaos',
    'The Poetry of Color',
    'Cascading Emotions',
    'Capturing Fragments',
    'Mysterious Abandon',
    'The Fragility of Life',
    'Exploring Dimensions',
    'Whispered Revelations',
    'Ephemeral Whispers',
    'Ethereal Euphoria',
    'Auroras Embrace',
    'Rhythms of the Earth',
    'Imaginary Creatures',
    'Metamorphosis of Time',
    'Unveiled Connections',
    'Enchanted Landscapes',
    'Colors of the Soul',
    'The Magic of Texture',
    'Whirling Dervish',
    'Hidden Symmetry',
    'Whispering Colors',
    'Whimsical Delights'
]

# Import all submodules.
from . import protocol
from . import reward
from . import utils
